spring:
  application:
    name: users-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/users-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
jwt:
  secret: this-is-very-strong-secret-key-with-32-bytes-long
  expiration: 3600000
  refresh-expiration: 604800000