spring:
  application:
    name: analytic-post-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: configserver:${spring.cloud.config.uri}
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/analytic-post-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}