server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VeleyHeight/config-repo
          clone-on-start: true
          search-paths: '{application}'

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:8761/eureka